artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/509864494489441911/56ddfa966eed4ed8a97cdcd6f5e381f9/artifacts
end_time: 1751560556863
entry_point_name: ''
experiment_id: '509864494489441911'
lifecycle_stage: active
run_id: 56ddfa966eed4ed8a97cdcd6f5e381f9
run_name: Default
run_uuid: 56ddfa966eed4ed8a97cdcd6f5e381f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1751560556843
status: 3
tags: []
user_id: mle-user
